# Generated by Django 4.0.5 on 2022-07-18 06:39

from django.db import migrations
from django.db import transaction


def write_author_balance(apps, schema_editor):
    # We can't import the Question model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    user = apps.get_model('auth', 'User').objects.get_or_create(id=1)[0]
    with transaction.atomic():
        apps.get_model('polls', 'AuthorBalance').objects.update(author=user)


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_authorbalance'),
    ]

    operations = [
        migrations.RunPython(write_author_balance)
    ]
