# Generated by Django 4.0.5 on 2022-07-29 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('polls', '0009_alter_authorbalance_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('1', 'Fixed'), ('2', 'Variable')], default=1, max_length=100)),
                ('author', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommonTariffTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='TariffFixed',
            fields=[
                ('commontariff_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.commontariff')),
                ('price', models.FloatField(default=0)),
            ],
            bases=('polls.commontariff',),
        ),
        migrations.CreateModel(
            name='TariffFixedTwo',
            fields=[
                ('commontarifftwo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.commontarifftwo')),
                ('price', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('polls.commontarifftwo',),
        ),
        migrations.CreateModel(
            name='TariffVariable',
            fields=[
                ('commontariff_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.commontariff')),
                ('price_the_question', models.FloatField(default=0)),
            ],
            bases=('polls.commontariff',),
        ),
        migrations.CreateModel(
            name='TariffVariableTwo',
            fields=[
                ('commontarifftwo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.commontarifftwo')),
                ('price_the_question', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('polls.commontarifftwo',),
        ),
    ]
