# Generated by Django 4.0.5 on 2022-07-29 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='profile',
        ),
    ]
