# Generated by Django 4.0.5 on 2022-07-29 10:10

from django.db import migrations
from django.db import transaction


def write_user_profile(apps, schema_editor):
    # We can't import the Question model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    users = apps.get_model('auth', 'User').objects.all()
    with transaction.atomic():
        for user in users:
            apps.get_model('polls', 'UserProfile').objects.create(profile=user)


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_rename_user_userprofile_profile'),
    ]

    operations = [
        migrations.RunPython(write_user_profile)
    ]
